[tool.ruff]
# Set what ruff should check for.
# See https://beta.ruff.rs/docs/rules/ for a list of rules.
select = [
    # TODO: Enable flake8-builtin and fix errors to fix variable name shadowing errors.
    # "A", # flake8-builtin errors.
    # TODO: Enable bugbear and fix errors.
    # "B", # bugbear errors
    # TODO: Enable flake8-django and fix errors.
    # "DJ", # flake8-django errors.
    "E", # pycodestyle errors
    "F", # pyflakes errors
    # TODO: Currently ruff doesn't have the ability to sort Django imports together.
    # "I", # import sorting
    "Q", # flake8-quotes errors
    "W", # pycodestyle warnings
]
line-length = 150  # To match flake8
target-version = 'py39'
extend-exclude = ["__pycache__", "docs", "assets", "static", "bedrock/externalfiles/files_cache"]

[tool.ruff.per-file-ignores]
"bedrock/settings/__init__.py" = ["F405"]

[tool.black]
line-length = 150  # To match flake8
target-version = ['py39']
include = '\.pyi?$'

[tool.isort]
combine_as_imports = true
default_section = 'THIRDPARTY'
include_trailing_comma = true
known_django = 'django'
known_first_party = 'bedrock,lib,pages'
profile = 'black'
sections = 'FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'
